-- PUBLIC.USERS definition

-- Drop table

-- DROP TABLE PUBLIC.USERS;

CREATE TABLE PUBLIC.USERS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	ALGORITHM CHARACTER VARYING(255),
	PASSWORD CHARACTER VARYING(255),
	USERNAME CHARACTER VARYING(255),
	CONSTRAINT CONSTRAINT_4D PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_4D ON PUBLIC.USERS (ID);

CREATE TABLE PUBLIC.AUTHORITY (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(255),
	USERS INTEGER,
	CONSTRAINT CONSTRAINT_F PRIMARY KEY (ID)
);
CREATE INDEX FKJJN8M316R4L5A9VAXBGYN53RD_INDEX_F ON PUBLIC.AUTHORITY (USERS);
CREATE UNIQUE INDEX PRIMARY_KEY_F ON PUBLIC.AUTHORITY (ID);


-- PUBLIC.AUTHORITY foreign keys

ALTER TABLE PUBLIC.AUTHORITY ADD CONSTRAINT FKJJN8M316R4L5A9VAXBGYN53RD FOREIGN KEY (USERS) REFERENCES PUBLIC.USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

INSERT INTO Users (id, username, password, algorithm)
VALUES ('1', 'sema', '$2a$10$xn3LI/AjqicFYZFruSwve.681477XaVNaUQbr1gioaWPn4t1KsnmG', 'BCRYPT'); --12345

INSERT INTO authority (id, name, Users)
VALUES ('1', 'READ', '1');
INSERT INTO authority (id, name, Users)
VALUES ('2', 'WRITE', '1');
